### ISSUE TITLE
French translation 

### ISSUE THREAD

**Issue by Salamandar** [swilmet/glib-gtk-book#11]
I can start it a bit, would be great to have this book in french !

**Comment by swilmet** [comment]
My native language is French, and I don't want to write such a book in French, because in English many more people can read it. The English version is far from a "1.0" version. There are still many changes here and there. It can be difficult to track all the changes and update the translation accordingly, because the translation is not done in a *.po file. So it's probably a bit early to think about a translation.

If you really want to write a French translation, I prefer that it's done in a separate repo.

**Comment by Salamandar** [comment]
Yup, and I am french too. Still, that would have been nice to have multiple translations in multiple branches !
The idea I had would've been to fork the master branch. Then, translate. Then, re-merge the master branch to see the changes, and do a "refactoring" commit.

    master---×---×changes-×-×-×………
              \                \
               ---×translations…×merge changes-×translate changes---………

**Comment by swilmet** [comment]
On GitHub you can easily fork a repo and host your branch there.
